### ISSUE TITLE
Backwards history search on Ctrl-R

### ISSUE THREAD

**Issue by fasterthanlime** [ftilde/ugdb#12]
First off, thanks for ugdb! I use it as my primary gdb front-end nowadays, and I enjoy it very much.

How hard would it be to add history support to ugdb? I know the "up" and "down" keys scroll through previous commands, but I really miss "Ctrl-R" (which I think is a built-in readline feature?) to search through previous commands.

I'm not too familiar with `unsegen`, so I don't know if it'd need any modifications to support that particular feature. I'm willing to help, but maybe you could point me where to look? That would surely save some time :)

**Comment by ftilde** [comment]
Glad to hear that you like ugdb!

I've actually looked into if it would be possible to somehow wrap `rustyline` in an unsegen widget and use that instead which would give all kinds of readline-like functionality for free, but came (at the time) to the conclusion that it would not be possible with the current API (of rustyline). Not sure if this has changed in the meantime.

Anyway, I think it wouldn't be too hard to implement history search manually.
There are two options on how to go about this:
1. Implement it in the [console of ugdb](https://github.com/ftilde/ugdb/blob/master/src/tui/console.rs):
Access the history of the `PromptLine` using [`previous_line`](https://docs.rs/unsegen/0.2.3/unsegen/widget/builtin/promptline/struct.PromptLine.html#method.previous_line). (Kind of an awkward API I realize now. We should probably add a `history(&self) -> &[String]` or something.) State could be stored in the `Console` using something like `history_search_state: Option<String>` and we would use a [`LineLabel`](https://docs.rs/unsegen/0.2.3/unsegen/widget/builtin/linelabel/struct.LineLabel.html) to display the history search text instead of the promptline temporarily. User interaction would need to be implemented somewhat similarly to the tab completion support in [`Container::input`](https://github.com/ftilde/ugdb/blob/master/src/tui/console.rs#L92) function.

2. Implement it as a feature of [`PromptLine`](https://docs.rs/unsegen/0.2.3/unsegen/widget/builtin/promptline/struct.PromptLine.html):
The history search state would be added to the `PromptLine` struct instead. Rendering should probably also be done in a separate LineLabel only visible when we are in history search mode. The mode could be entered using a function on `PromptLine` and if active would change the `Writable`, `Navigatable` and `Scrollable` behaviour as well as the Widget implementation (i.e., use the new LineLabel instead of self.line). How the API additions work could relatively easily shown in tests. (You could also clone unsegen alongside ugdb and [overwrite the unsegen dependency temporarily](https://github.com/ftilde/ugdb/blob/master/Cargo.toml#L54) during the implementation). In ugdb the only required change would be to enter the history search mode on Ctrl-R in [`Container::input`](https://github.com/ftilde/ugdb/blob/master/src/tui/console.rs#L92).

I think I would prefer option 2 as other users of `PromptLine` (... if there are any :D) would benefit from this as well. What do you think?

**Comment by ftilde** [comment]
I've implemented history search in `PromptLine` which is now available in ugdb as well. Let me know if you find any issues with it!

**Comment by fasterthanlime** [comment]
> I've implemented history search in `PromptLine` which is now available in ugdb as well. Let me know if you find any issues with it!

Sorry for the delay — I just tried history search in `ugdb` and it works exactly as I'd expect (I like the 🔍 emoji!). I've had issues quitting ugdb (with q/quit) and entering a shell (with `shell`) seemed to hang the whole thing, but that's non-history-related 😅

**Comment by ftilde** [comment]
On 11.06.2021 03:36, Amos Wenger wrote:
>> I've implemented history search in `PromptLine` which is now available in ugdb as well. Let me know if you find any issues with it!
>
>Sorry for the delay — I just tried history search in `ugdb` and it works exactly as I'd expect (I like the 🔍 emoji!). I've had issues quitting ugdb (with q/quit) and entering a shell (with `shell`) seemed to hang the whole thing, but that's non-history-related 😅
Oh, I wasn't even aware that this command existed. The issue here is 
basically the same as #5: gdb starts another process and lets it take 
over stdout. The process in turn of course does not adhere to the gdbmi 
spec that we use to communicate with gdb, and ugdb gets quite confused. 
What's really problematic is that we (as far as I know) have no way to 
determine that the process has exited so that we can treat the output as 
gdbmi messages again, since the termination of the command *is 
communicated via gdbmi*. At the same time, the child process is of 
course free to output something that *looks like* gdbmi (e.g. `echo 
123^done`).

I really have no idea how to fix this at the moment. :( As ugdb just 
hangs at `shell` as you described, I have just disallowed that command 
for now. The good news for this particular case is that ugdb properly 
supports job control/suspension. A workaround might hence be to just 
press ctrl-z to get back to the shell that started ugdb and return with 
`fg`. This might work for you?

**Comment by fasterthanlime** [comment]
> A workaround might hence be to just press ctrl-z to get back to the shell that started ugdb and return with `fg`. This might work for you?

It's not quite the same, but I'm very convinced by your explanation that doing otherwise would be a big hassle. I got exhausted just thinking about filing a bug against GDB and waiting 8 years for everyone to upgrade to a version of Ubuntu that has the newer GDB so uhh yeah the workaround will do just fine 👍  Thanks for looking into this!
