### ISSUE TITLE
Configurable layout

### ISSUE THREAD

**Issue by ftilde** [ftilde/ugdb#3]
Dynamic layouting of containers/windows should be possible, but would require changes in [unsegen](https://github.com/ftilde/unsegen) as well.

**Comment by ericonr** [comment]
A first step could be enabling static layout controlled by command line options (it seems to me like that would be easier, but I'm not familiar with unsegen's API). That would be extra useful in my case, because I'm an embedded programmer, so there isn't much of a reason for nearly half the screen being occupied by stdout from the program being debugged.

As I said in the issue I created, at some point I'd be interested in helping out.

**Comment by ftilde** [comment]
> A first step could be enabling static layout controlled by  command line options (it seems to me like that would be easier, but I'm  not familiar with unsegen's API).

I think a config file would actually more straight forward, because we need some way of representing the layout tree. I already have some ideas on how to implement that in the back of my head, but decided to work on tab completion first. Changes in unsegen are definitely necessary, but that's not a really a problem.

> That would be extra useful in my case, because I'm an embedded programmer, so there isn't much of a reason for nearly half the screen being occupied by stdout from the program being debugged.

If you're *really* eagerly waiting for another layout, you could just change edit the [corresponding lines](https://github.com/ftilde/ugdb/blob/master/src/main.rs#L368) in main.rs for your own build. That should actually be quite straight forward even if you're not familiar with rust.

> As I said in the issue I created, at some point I'd be interested in helping out.

Great! Looking forward to it!

**Comment by ftilde** [comment]
With version 0.1.10 the layout can now be changed using the `--layout` cmdline parameter and the !layout command.
